BOARD_WIDTH = BOARD_HEIGHT = 768
MOVE_LOG_PANEL_WIDTH = 380
MOVE_LOG_PANEL_HEIGHT = BOARD_HEIGHT
DIMENSION = 8
SQ_SIZE = BOARD_HEIGHT / DIMENSION
MAX_FPS = 15
IMAGES = {}

#options: "human" or "ai"
WHITE_PLAYER = "ai"
BLACK_PLAYER = "human"

PLAYER1 = WHITE_PLAYER == "human"

PLAYER2 = BLACK_PLAYER == "human"
